spring:
  application:
    name: '@project.name@'
  main:
    banner-mode: "off"
logging:
  pattern:
    console: "[%date{yyyy-MM-dd HH:mm:ss:SSS}] [%level] [%thread] [%logger] %mdc%n  + Message: %message%replace(%ex){'^(?!$)', '\n+ Throwable: ' }%n%nopex"  
ibus:
  container:
    hostName: ${HOST:localhost}
    jvmName: ${HOSTNAME}
    scenarioName: ${spring.application.name}
info:
  build:
    artifact: '@project.artifactId@'
    name: ${spring.application.name}
    description: '@project.description@'
    version: '@project.version@'
