spring:
  application:
    name: 'CoreFinancialClearanceEligibilityContainer'
  main:
    banner-mode: "off"
logging:
  pattern:
    console: "[%date{yyyy-MM-dd HH:mm:ss:SSS}] [%level] [%thread] [%logger] %mdc%n  + Message: %message%replace(%ex){'^(?!$)', '\n+ Throwable: ' }%n%nopex"  
ibus:
  container:
    hostName: ${HOST:localhost}
    jvmName: ${HOSTNAME}
    scenarioName: ${spring.application.name}
info:
  build:
    artifact: 'corefinancialclearanceeligibility-container'
    name: ${spring.application.name}
    description: 'corefinancialclearanceeligibility-container'
    version: '1.2.0-SNAPSHOT'
